{{- define "niomon-responder.env" -}}
- name: KAFKA_TOPIC_IN_SUCCESS
  value: "ubirch-common-message-json"
- name: KAFKA_TOPIC_IN_ERROR
  value: "ubirch-niomon-error-json"
- name: KAFKA_TOPIC_OUT
  value: "ubirch-common-response-json"
- name: UUID_NORMAL
  value: "{{ .Values.serverUuid }}"
- name: UUID_ERROR
  value: "{{ .Values.serverUuid }}"
{{- end -}}

{{- $deployment := (dict "envStr" (include "niomon-responder.env" .)) -}}

{{- $_ := set $deployment "Root" . -}}
{{- $_ := set $deployment "name" "responder" -}}
  {{- $_ := set $deployment "replicas" .Values.responder.replicas -}}

{{ template "niomon.deployment" $deployment }}

---

{{ template "niomon.service" $deployment }}

---

{{ template "niomon.prometheus.monitor" $deployment}}
